### ISSUE TITLE
[BUG] Time display is not working

### ISSUE THREAD

**Issue by marchein** [androidseb25/iGotify-Notification-Assistent#37] opened 2024-02-09 21:19 UTC
**Describe the bug**
If I receive a notification within the list the notification date is always shown as (in German) "vor 0s" but once I select the entry it shows the correct time and date.

**Expected behavior**
Show the same time duration as in the detail view.

**Screenshots**
![image](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/4535391/be497b6c-479f-4c91-8915-9e88ee797a71)
![image](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/4535391/bc3a7345-4504-4d55-a796-f6cde0a04872)

**Smartphone (please complete the following information):**
 - Device: iPhone 15
 - OS: iOS 17.3.1
 - Version of Container 1.1.0.0
 - Version of iGotify 1.1.1

**Additional context**

**Comment by androidseb25** [comment] 2024-02-09 21:23
the problem is maybe a parsing error of the date, i take a look at this.

**Comment by androidseb25** [comment] 2024-02-21 20:24
Did you can show me the time string from the Uptime Kuma message? You can find it in the logs from the assistent...

Because i can't reproduce the error :/

**Comment by androidseb25** [comment] 2024-02-26 20:50
Will be fixed Wednesday at 18 o'clock CET with the release of 1.2

**Closed by androidseb25** 2024-02-26 20:50 UTC
Labels: bug
