### ISSUE TITLE
[BUG] Not possible to use this app since latest version

### ISSUE THREAD

**Issue by yeyeoke** [androidseb25/iGotify-Notification-Assistent#73] opened 2024-07-09 08:05 UTC
**Describe the bug**
If the app wasn't successfully configured before downloading the new version from AppStore, we get locked out, we're just stuck on a screen that shows that our endpoint isn't updated to the latest version (since it doesn't have an endpoint configured, this is very much expected).

I tried removing the app and restarting the phone, but that doesn't seem to clear the app data. 

**Expected behavior**
We need a way to clear the app data and start all over again. 

**Screenshots**
![iOS](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/12892950/3dfe4665-193f-4486-a68a-a4cf3e1a7e7b)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: 17.5.1
 - Version of Container: N/A
 - Version of iGotify: 1.3.0

**Comment by androidseb25** [comment] 2024-07-09 08:06
#72

**Comment by Reginard** [comment] 2024-07-09 08:33
I have the same result with an iPad that didn't have iGotify installed ever. Once installed it shows the same issue

**Comment by androidseb25** [comment] 2024-07-09 13:25
Update is accepted and live

**Comment by DonPablo1010** [comment] 2024-07-09 14:40
Fix works on one device / instance where i left the app as it was. On another device / instance where i deleted the app on ios and reinstalled it, the app stills hangs on the blue screen where it can't find a latest version instance. I'm not able to reenter the urls etc. of gotify and igotify...

**Comment by androidseb25** [comment] 2024-07-09 14:41
Closed duplicate of #72

**Closed** 2024-07-09 14:40 UTC
Labels: bug
